# $tcsh: .travis.yml,v 1.2 2014/03/10 12:41:27 kim Exp $
language: c
compiler:
 - gcc
 - clang
before_install:
 - sudo apt-get update -q=2
 - sudo apt-get install -q=2 automake libtinfo-dev make
script:
 - ./configure
 - make -j4
 - make check
